name: Optimized Dev Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            /home/runner/.gradle/caches
            /home/runner/.gradle/wrapper
          key: ${{ runner.os }}-deps-${{ hashFiles('pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get version and build number
        id: version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed -n 's/version: \([0-9]*\.[0-9]*\.[0-9]*\).*/\1/p')
          echo "VERSION=$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "BUILD_NUMBER=${{ github.run_number }}" >> $GITHUB_OUTPUT

      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

      - name: Generate Release Keystore
        run: |
          cd android/app
          chmod +x ../generate-keystore.sh
          ../generate-keystore.sh
          cd ../..

      - name: Build Release APK
        run: flutter build apk --release --build-name=${{ steps.version.outputs.VERSION }} --build-number=${{ github.run_number }}
        env:
          JAVA_HOME: /usr/lib/jvm/temurin-17-jdk-amd64

      - name: Rename APK
        id: rename_apk
        run: |
          APK_NAME="daily-inc-v${{ steps.version.outputs.VERSION }}+${{ github.run_number }}.apk"
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/$APK_NAME
          echo "apk_path=build/app/outputs/flutter-apk/$APK_NAME" >> $GITHUB_OUTPUT

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release
          path: ${{ steps.rename_apk.outputs.apk_path }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        run: sudo apt update && sudo apt install -y libgtk-3-dev pkg-config libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build linux --release
      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-release
          path: build/linux/x64/release/bundle

  create-draft-release:
    needs: [build-android]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: android-release
          path: artifacts/android

      - name: Get commit info
        id: commit_info
        run: |
          echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          echo "COMMIT_MSG=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Create draft release
        uses: softprops/action-gh-release@v2
        with:
          name: Development Build v${{ needs.build-android.outputs.version }}+${{ github.run_number }}
          tag_name: v${{ needs.build-android.outputs.version }}+${{ github.run_number }}
          draft: true
          prerelease: true
          body: |
            Automated development build
            Commit: ${{ steps.commit_info.outputs.COMMIT_MSG }}
          files: artifacts/android/*